# ---
# - name: Unzip artifact
#   unarchive:
#     src: artifact.tar.gz
#     dest: ~/

# - name: Start backend
#   shell: |
#     cd ~/backend 
#     npm install
#     export ANSIBLE_HOST_KEY_CHECKING=False
#     pm2 stop default
#     pm2 start npm -- start

---
- name: copy dist backend folder to ec2 server
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: prepare binaries
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .
- name: start server
  become: true
  shell: |
    cd /home/ubuntu
    pm2 start npm --name backend -- start